name: Unit tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.727'
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
      - name: Install npm deps
        run: npm install
      - name: Run tests
        run: bin/kaocha
